### ISSUE TITLE
Issue on python 3.6.2

### ISSUE THREAD

**Issue by karimone** [j0hnsmith/django-pipeline-browserify#24]
Hello, I'm using your plugin to compile react code. I recently switch to python 3.6.2. During the collectstatic I have this issue:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 139, in collect
    for original_path, processed_path, processed in processor:
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/pipeline/storage.py", line 33, in post_process
    packager.pack_javascripts(package)
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/pipeline/packager.py", line 124, in pack_javascripts
    return self.pack(package, self.compressor.compress_js, js_compressed, templates=package.templates, **kwargs)
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/pipeline/packager.py", line 116, in pack
    force=True,
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/pipeline/packager.py", line 106, in compile
    force=force,
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/pipeline/compilers/__init__.py", line 56, in compile
    return list(executor.map(_compile, paths))
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/pipeline/compilers/__init__.py", line 40, in _compile
    outdated = compiler.is_outdated(infile, outfile)
  File "/Users/karim/Envs/cml3/lib/python3.6/site-packages/pipeline_browserify/compiler.py", line 97, in is_outdated
    for dep_file in dep_list.strip().split('\n'):
TypeError: a bytes-like object is required, not 'str'
```

I'm currently using `django-pipeline-browserify 0.6.1`

Any suggestion?

**Comment by natevw** [comment]
This was fixed by https://github.com/j0hnsmith/django-pipeline-browserify/pull/23 but sounds like that has not been published to PyPi yet.

@j0hnsmith could you publish a 0.6.2?

**Comment by karimone** [comment]
The `setup.py` still refer to 0.6.1.

**Comment by j0hnsmith** [comment]
Updated in github to `0.6.2` but having trouble pushing to pypi, will resolve asap.

**Comment by j0hnsmith** [comment]
So I managed to upload `0.6.2` to pypi but the description is gone.
